### ISSUE TITLE
SCOPE_IDENTITY()

### ISSUE THREAD

**Issue by hyperlance** [mj1856/SqlServerTimeZoneSupport#23] opened 2017-02-22 03:36 UTC
In the procedure AddZone SCOPE_IDENTITY() is used.  SCOPE_IDENTITY() returns the last ID of ANY table inserted, not the one you are inserting to. Rather the OUTPUT clause should be used return the ID. The following code should be used.

    DECLARE @Output TABLE (ID INT)

    INSERT INTO [Tzdb].[Zones] ([Name]) 
	OUTPUT Inserted.Id INTO @Output
	VALUES (@Name)

    SET @id = (SELECT ID FROM @Output)

**Comment by srutzky** [comment] 2017-02-22 06:08
@hyperlance The statement made above regarding `SCOPE_IDENTITY()` is incorrect. It returns the most recent Identity value in the _current_ scope, and hence it is being used correctly in the `AddZone` stored procedure. It is possible that you are confusing this with `@@IDENTITY` which has been problematic as it returns the most recent Identity value across all scopes in the current session (i.e. inserts made in a Trigger that was fired from the insert made into a table in the current scope). `SCOPE_IDENTITY()` does not have that problem and should be used here.

Please see the MSDN documentation for this: https://msdn.microsoft.com/en-us/library/ms190315.aspx

No changes should be made to the AddZone stored procedure (at least not for anything related to `SCOPE_IDENTITY()` ).

**Comment by hyperlance** [comment] 2017-02-22 06:20
Yes, but there are still problems with using it. See http://www.sqlbadpractices.com/how-not-to-retrieve-identity-value/

**Comment by srutzky** [comment] 2017-02-22 06:40
@hyperlance According to that post you linked to, the problem is largely academic as it requires a parallel plan to be involved. And that same post even states that the problem won't happen with `INSERT INTO table VALUES ()`, which is what the `AddZone` stored procedure is using. And, the Microsoft KB article that is linked to from that post indicates that the problem was fixed as of SQL Server 2008 R2, SP2 (essentially).

The `OUTPUT` clause should be used when needing to capture multiple Identity values resulting from a set-based `INSERT`. But it is unnecessary overkill to use it in this context (i.e. `INSERT ... VALUES` ).

**Comment by hyperlance** [comment] 2017-02-22 07:09
Best practice always wins out in my book. If you start short cutting then you make that a habit and you end up with sloppy code.

**Comment by srutzky** [comment] 2017-02-22 15:52
> Best practice always wins out in my book.

I tend to agree. And that is why I am saying that in this context, `SCOPE_IDENTITY` _is_ the best practice. The post you linked to, as well as the Microsoft KB article that post linked to, both clearly state that:

1. `SCOPE_IDENTITY` has problems _only_ when parallel plans are involved.
1. Doing `INSERT INTO ... VALUES` does _not_ generate a parallel plan.

Hence, `SCOPE_IDENTITY` is never a problem when using `INSERT INTO...VALUES`, and is the best practice in that context. I have worked on systems with 5000+ transactions per second and we used `SCOPE_IDENTITY` in all cases except when multiple rows were being inserted, in which case we used the `OUTPUT` clause. We never had a problem because that is how you are supposed to do things, and neither the post you linked to nor its linked Microsoft KB article contradict that.

The only problem seems to be that the post you linked to makes an unsubstantiated logical leap at the end when stating that "The recommended way of retrieving identity values ... is to use the OUTPUT clause". That statement needed to be qualified with "when dealing with parallel plans". And the code example at the end showing `INSERT INTO...VALUES` using the `OUTPUT` clause makes no sense, and that pattern is _not_ what is being recommended in that linked Microsoft KB article.

**Closed as completed** 2017-04-24 16:23 UTC
